### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Gedehamsen021** [bondolo/tribaltrouble#4]
your ant script are broken :(
i passed my all week trying make a server to play with my friends :(

can you help me to build your fork?

**Comment by bondolo** [comment]
Can you post the output?

**Comment by Gedehamsen021** [comment]
when i try compile and run antbuild.xml of server

```
"C:\Program Files (x86)\Java\jdk1.8.0_281\bin\java.exe" -Xmx128m -Xss2m "-Dant.home=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant" "-Dant.library.dir=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-antlr.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-apache-bcel.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-apache-bsf.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-apache-log4j.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-apache-oro.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-apache-regexp.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-apache-resolver.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-apache-xalan2.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-commons-logging.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-commons-net.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-jai.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-javamail.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-jdepend.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-jmf.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-jsch.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-junit.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-junit4.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-junitlauncher.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-launcher.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-netrexx.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-swing.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-testutil.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant-xz.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\ant\lib\ant.jar;C:\Program Files (x86)\Java\jdk1.8.0_281\lib\tools.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1\lib\idea_rt.jar" com.intellij.rt.ant.execution.AntMain2 -logger com.intellij.rt.ant.execution.IdeaAntLogger2 -inputhandler com.intellij.rt.ant.execution.IdeaInputHandler -buildfile C:\Users\gede\IdeaProjects\tribaltrouble2\server\antbuild.xml run
antbuild.xml
get-cores
Number of cores: 4
init
compile-common
get-cores
Number of cores: 4
init
compiledeps
compile
C:\Users\gede\IdeaProjects\tribaltrouble2\common\common.xml:55: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
compiledeps
compile
C:\Users\gede\IdeaProjects\tribaltrouble2\common\common.xml:55: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
Compiling 8 source files to C:\Users\gede\IdeaProjects\tribaltrouble2\server\build\classes
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\Authenticator.java:16: error: cannot find symbol
import com.oddlabs.registration.RegistrationInfo;
                               ^
  symbol:   class RegistrationInfo
  location: package com.oddlabs.registration
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\MatchmakingServer.java:11: error: cannot find symbol
import com.oddlabs.util.DBUtils;
                       ^
  symbol:   class DBUtils
  location: package com.oddlabs.util
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\MatchmakingServer.java:20: error: cannot find symbol
import com.oddlabs.registration.RegistrationInfo;
                               ^
  symbol:   class RegistrationInfo
  location: package com.oddlabs.registration
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:32: error: cannot find symbol
import com.oddlabs.util.DBUtils;
                       ^
  symbol:   class DBUtils
  location: package com.oddlabs.util
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\routerserver\RouterServer.java:7: error: cannot find symbol
import com.oddlabs.util.DBUtils;
                       ^
  symbol:   class DBUtils
  location: package com.oddlabs.util
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\Authenticator.java:180: error: cannot find symbol
					RegistrationInfo reg_info = (RegistrationInfo)reg_key.getObject();
					^
  symbol:   class RegistrationInfo
  location: class Authenticator
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\Authenticator.java:180: error: cannot find symbol
					RegistrationInfo reg_info = (RegistrationInfo)reg_key.getObject();
					                             ^
  symbol:   class RegistrationInfo
  location: class Authenticator
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\MatchmakingServer.java:64: error: cannot find symbol
		DBUtils.initConnection("jdbc:mysql://localhost/oddlabs", "matchmaker", "U46TawOp");
		^
  symbol:   variable DBUtils
  location: class MatchmakingServer
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\MatchmakingServer.java:135: error: cannot find symbol
			DBUtils.postHermesMessage("elias, xar, jacob, thufir: Matchmaking service crashed!");
			^
  symbol:   variable DBUtils
  location: class MatchmakingServer
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:38: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT username FROM registrations R WHERE R.reg_key = ? AND NOT R.disabled AND NOT R.banned");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:59: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT username FROM registrations R WHERE lower(R.username) = lower(?)");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:80: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("UPDATE registrations R SET username = ?, email = ?, password = ? WHERE R.reg_key = ? AND R.username IS NULL AND R.password IS NULL AND R.email IS NULL");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:99: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT username, password FROM registrations R WHERE lower(R.username) = lower(?) AND R.password = ? AND NOT R.disabled AND NOT R.banned");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:121: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT nick, rating, wins, losses, invalid FROM profiles P, registrations R WHERE P.reg_id = R.id AND R.username = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:155: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT rating, wins, losses, invalid FROM profiles P, registrations R WHERE P.reg_id = R.id AND R.username = ? AND P.nick = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:180: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("UPDATE registrations R SET last_used_profile = ? WHERE R.username = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:197: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT last_used_profile FROM registrations R WHERE R.username = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:220: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT id FROM registrations R WHERE R.username = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:241: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT nick FROM profiles P WHERE lower(P.nick) = lower(?)");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:262: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("INSERT INTO game_reports (game_id, tick, team1, team2, team3, team4, team5, team6) " + 
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:286: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("INSERT INTO connections (game_id, nick1, nick2, priority) " + 
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:307: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("INSERT INTO profiles (reg_id, nick, rating, wins, losses, invalid) " + 
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:328: error: cannot find symbol
				PreparedStatement stmt = DBUtils.createStatement("INSERT INTO deleted_profiles (reg_id, nick, rating, wins, losses, invalid) " + 
				                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:347: error: cannot find symbol
				PreparedStatement stmt = DBUtils.createStatement("DELETE FROM profiles WHERE nick = ?");
				                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:375: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("UPDATE profiles P SET " + field + " = " + field + " + 1 WHERE P.nick = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:389: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("UPDATE profiles P SET rating = rating + ? WHERE P.nick = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:412: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT " + int_field + " FROM profiles P WHERE P.nick = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:433: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT value FROM settings S WHERE S.property = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:464: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT nick, rating, wins, losses, invalid FROM profiles P WHERE P.wins >= "+ GameSession.MIN_WINS_FOR_RANKING +" ORDER BY rating DESC, (wins - losses) DESC, wins DESC LIMIT ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:498: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("INSERT INTO games (player1_name, time_create, name, rated, speed, size, hills, trees, resources, mapcode, status) " + 
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:525: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("SELECT id FROM games WHERE player1_name = ? AND status = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:548: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("UPDATE games G SET status = ? WHERE G.status = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:563: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("UPDATE games G SET status = ? WHERE G.player1_name = ? AND G.status = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:585: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("UPDATE games G SET " + participant_sql + "G.time_start = ?, G.status = ? WHERE G.id = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:618: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("UPDATE games G SET G.time_stop = ?, G.status = ?, G.winner = ? WHERE G.id = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:636: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("INSERT INTO online_profiles (nick) VALUES (?)");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:651: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("DELETE FROM online_profiles WHERE nick = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:666: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("UPDATE online_profiles O SET O.game_id = ? WHERE O.nick = ?");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\matchserver\DBInterface.java:682: error: cannot find symbol
			PreparedStatement stmt = DBUtils.createStatement("TRUNCATE TABLE online_profiles");
			                         ^
  symbol:   variable DBUtils
  location: class DBInterface
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\routerserver\RouterServer.java:68: error: cannot find symbol
			DBUtils.initConnection("jdbc:mysql://localhost/oddlabs", "matchmaker", "U46TawOp");
			^
  symbol:   variable DBUtils
  location: class RouterServer
C:\Users\gede\IdeaProjects\tribaltrouble2\server\classes\com\oddlabs\routerserver\RouterServer.java:69: error: cannot find symbol
			DBUtils.postHermesMessage("elias, xar, jacob, thufir: Router crashed!");
			^
  symbol:   variable DBUtils
  location: class RouterServer
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
41 errors
C:\Users\gede\IdeaProjects\tribaltrouble2\common\common.xml:55: Compile failed; see the compiler error output for details.
	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1425)
	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:1133)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:834)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.Main.start(Main.java:190)
	at org.apache.tools.ant.Main.main(Main.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.ant.execution.AntMain2.main(AntMain2.java:31)
C:\Users\gede\IdeaProjects\tribaltrouble2\common\common.xml:55: Compile failed; see the compiler error output for details.
	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1425)
	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:1133)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:834)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.Main.start(Main.java:190)
	at org.apache.tools.ant.Main.main(Main.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.ant.execution.AntMain2.main(AntMain2.java:31)
C:\Users\gede\IdeaProjects\tribaltrouble2\common\common.xml:55: Compile failed; see the compiler error output for details.
	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1425)
	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:1133)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
	at org.apache.tools.ant.Main.runBuild(Main.java:834)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.Main.start(Main.java:190)
	at org.apache.tools.ant.Main.main(Main.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.ant.execution.AntMain2.main(AntMain2.java:31)

Ant build completed with 3 errors and 212 warnings in 1s at 16/04/2021 14:53
```

**Comment by Gedehamsen021** [comment]
and i cannot found the compiler for create tt file

**Comment by bondolo** [comment]
Ah, I don't believe the server is complete. I have never tried to compile it. In the original repo they include the notes:

> Please note that the multiplayer server referenced in these builds, is no longer available.

and

> Setting up a server is a lot more complex, and not something we have done in many years. It will take some work to get it working, but try looking at the server folder and see if you can figure it out. At the very least, you should know a bit about setting up a MySQL server.

I have never tried to build or setup a server.

**Comment by Gedehamsen021** [comment]
oh ok, i will try remake the server, ty :)
